/* eslint-disable */

export enum ScreenDashBoard {
    DASH_BOARD = 'DASH_BOARD',
    CREATE_SYSTEM_NOTIFICATION = 'CREATE_SYSTEM_NOTIFICATION',
    DETAIL_SYSTEM_NOTIFICATION = 'DETAIL_SYSTEM_NOTIFICATION',
    UPDATE_SYSTEM_NOTIFICATION = 'UPDATE_SYSTEM_NOTIFICATION',
}