/* eslint-disable */

export enum RoleMtgEnum {
    HOST = 'HOST',
    CONTROL_BOARD = 'CONTROL_BOARD',
    DIRECTOR_GENERAL_DIRECTOR = 'DIRECTOR_GENERAL_DIRECTOR',
    ADMINISTRATIVE_COUNCIL = 'ADMINISTRATIVE_COUNCIL',
    SHAREHOLDER = 'SHAREHOLDER',
}

export enum ScreenSettingRole {
    SETTING_ROLE_SYS = 'SETTING ROLE SYS',
    SETTING_ROLE_MTG = 'SETTING ROLE MTG',
}

export enum TypeRoleMeeting {
    NULL_MEETING = 'NULL_MEETING',
    SHAREHOLDER_MEETING = 'SHAREHOLDER_MEETING',
    BOARD_MEETING = 'BOARD_MEETING',
    BOTH_MEETING = 'BOTH_MEETING',
}
